# The address from which to send all application emails
EMAIL_FROM: "Hourglass <hourglass@example.com>"

# In a perfect world, how many hours per person per week
EXPECTED_WEEKLY_CLIENT_HOURS: "32"
EXPECTED_WEEKLY_INTERNAL_HOURS: "8"

# Harvest credentials and configuration
HARVEST_INTERNAL_CLIENT: "Internal" # The client in Harvest to consider internal
HARVEST_PASSWORD: "secret"
HARVEST_SUBDOMAIN: "example"
HARVEST_TIME_ZONE: "Eastern Time (US & Canada)" # rake time:zones:all
HARVEST_USERNAME: "jane@example.com" # Must be an admin

# Mandrill SMPT credentials and configuration
MANDRILL_DOMAIN: "example.com"
MANDRILL_PASSWORD: "hTgvuxadFPSYJ4RMmapnoA" # Fake; must generate API key
MANDRILL_USERNAME: "hourglass@example.com"

# The number of hours considered to be taken off during a PTO day
PTO_DAY_HOURS: "8.0"

# The number of days (including today) to display on the Panic Status Board
STATUSBOARD_DAYS: "7"

# A secure URL to the PTO calendar provided by Zenefits
ZENEFITS_PTO_CALENDAR_URL: "https://secure.zenefits.com/pto_calendar/784045?token=WLltlFOzjp" # Fake
